const LIVE_SNAPSHOT_SCHEMA_VERSION = "live-pre-round-snapshot/v1";
const LIVE_SNAPSHOT_MANIFEST_SCHEMA_VERSION = "live-pre-round-snapshot-manifest/v1";
const LIVE_SNAPSHOT_AUDIT_SCHEMA_VERSION = "live-pre-round-snapshot-audit/v1";
const CANONICALIZATION_VERSION = "canonical-json/v1";
const HASH_ALGORITHM = "sha256";

const CAPTURE_PHASE = {
  PRE_MARKET_CLOSE: "PRE_MARKET_CLOSE",
  POST_MARKET_CLOSE: "POST_MARKET_CLOSE",
  UNKNOWN: "UNKNOWN"
};

const AVAILABILITY = {
  AVAILABLE: "AVAILABLE",
  UNAVAILABLE: "UNAVAILABLE",
  NOT_CAPTURED: "NOT_CAPTURED",
  NOT_APPLICABLE: "NOT_APPLICABLE"
};

module.exports = {
  AVAILABILITY,
  CANONICALIZATION_VERSION,
  CAPTURE_PHASE,
  HASH_ALGORITHM,
  LIVE_SNAPSHOT_AUDIT_SCHEMA_VERSION,
  LIVE_SNAPSHOT_MANIFEST_SCHEMA_VERSION,
  LIVE_SNAPSHOT_SCHEMA_VERSION
};
